from walking import Llama, Kangaroo, Capybara, Pig, Tortoise
from swimming import Ray, SeaTurtle, Dolphin, Seahorse, Seal
from slithering import Snake, Lizard, Duck, Terrapin, Koi


miss_fuzz = Llama("Miss Fuzz", "domestic llama", "morning", "grass")
bouncer = Kangaroo("Bouncer", "miniature kangaroo", "midday", "grass")
satsuma = Capybara("Satsuma", "capybara", "midday", "fruit salad")
daisy = Pig("Daisy", "teacup pig", "afternoon", "pig chow")
ryuuji = Tortoise("Ryuuji", "leopard tortoise", "afternoon", "fruit salad")
sora = Ray("Sora", "manta ray", "crustaceans")
suzu = SeaTurtle("Suzu", "leatherback sea turtle", "crustaceans")
pebble = Dolphin("Pebble", "bottlenose dolphin", "fish")
sunny = Seahorse("Sunny", "dwarf seahorse", "crustaceans")
kairi = Seal("Kairi", "gray seal", "fish")
seraphina = Snake("Seraphina", "rosy boa", "mice")
toki = Lizard("Toki", "tokay gekko", "crickets")
hua = Duck("Hua", "pekin duck", "seed & grains mix")
zhen = Terrapin("zhen", "golden coin turtle", "crustaceans")
hoshi = Koi("Hoshi", "yamabuki ogon", "pellets")
print(miss_fuzz)
print(bouncer)
print(satsuma)
print(daisy)
print(ryuuji)
print(sora)
print(suzu)
print(pebble)
print(sunny)
print(kairi)
print(seraphina)
print(toki)
print(hua)
print(zhen)
print(hoshi)
